import type { InputEvidence, ModelEvidence, Prediction } from "../types";

const number = (value: number | null | undefined, digits = 4) => value == null ? "—" : value.toFixed(digits);
const date = (value: string | null | undefined) => value?.replace(/^(\d{4})(\d{2})(\d{2})$/, "$1-$2-$3") ?? "기록 없음";

function InputTable({ inputs, raw }: { inputs: InputEvidence[]; raw?: boolean }) {
  return <div className="evidence-table-wrap"><table className="evidence-table"><thead><tr><th scope="col">입력 변수</th>{raw ? <th scope="col">최신 API 값</th> : null}<th scope="col">실제 모델 입력값</th><th scope="col">처리 방법</th></tr></thead><tbody>{inputs.map(input => <tr key={input.name}><th scope="row">{input.name}{input.source_key ? <small>{input.source_key}</small> : null}</th>{raw ? <td>{number(input.raw_value)}</td> : null}<td>{number(input.model_value)}</td><td>{input.treatment}</td></tr>)}</tbody></table></div>;
}

export function PredictionEvidence({ prediction, model, error, loading }: { prediction?: Prediction | null; model?: ModelEvidence | null; error?: string; loading: boolean }) {
  const calculation = prediction?.calculation;
  const audit = model?.latest_training;
  const missing = calculation?.base_inputs.filter(input => input.raw_value == null) ?? [];
  return <section className="evidence-panel panel" aria-labelledby="prediction-evidence-title">
    <div className="evidence-heading"><div><span className="eyebrow">PREDICTION LAB · TRACE</span><h2 id="prediction-evidence-title">예측 온도 계산 근거 및 과정</h2><p>이번 예측의 실제 입력과 계산값을 확인하는 테스트용 분석 창입니다.</p></div><span className="evidence-tag">{calculation ? "실제 추론 기록" : "입력 대기"}</span></div>
    {model ? <>
      <div className="evidence-summary"><div><span>일자료 입력 출처</span><strong>{model.daily_source}</strong><small>시간자료는 오늘 날씨 표시 전용 · 현재 모델 학습 입력에는 미포함</small></div><div><span>입력 구성</span><strong>기본 {model.base_feature_count} → 파생 포함 {model.engineered_feature_count} → 최종 {model.model_input_count}개</strong><small>최종 입력에는 학습된 결측 표시 변수가 포함될 수 있습니다.</small></div><div><span>현재 배포 모델</span><strong>{model.model_version}</strong><small>예측 재시도는 재추론만 수행 · 관측 캐시 {model.cache_ttl_seconds / 60}분</small></div></div>
      <div className="evidence-flow" aria-label="예측 처리 과정"><div><b>01</b><h3>관측자료 수집</h3><p>{calculation ? `${calculation.history_start} ~ ${calculation.history_end} · ${calculation.source_row_count}행` : "최근 일자료 조회"}</p><small>서울 ASOS 관측을 날짜순 정렬·중복 제거</small></div><div><b>02</b><h3>전처리·변수 생성</h3><p>44개 변수와 최근 기상 흐름</p><small>강수·적설 등 결측은 0, 나머지는 과거값 ffill → 남은 결측은 학습 중앙값. 1·2·3·7·14일 lag, 3·7·14일 이동통계와 계절 변수를 계산합니다.</small></div><div><b>03</b><h3>기온 변화 예측</h3><p>CatBoost + LightGBM</p><small>관측 평균기온에 각 모델의 예상 변화량을 더합니다.</small></div><div><b>04</b><h3>가중 결합·저장</h3><p>{prediction ? `${prediction.predicted_for_date} 평균기온` : `입력일 기준 t+${model.forecast_offset_days}`}</p><small>검증 구간에서 정한 가중치로 결합. 날짜 확인 후 MySQL 저장.</small></div></div>
    </> : <p className="evidence-notice">{loading ? "모델 근거를 불러오는 중입니다." : "모델 메타데이터를 불러오지 못했습니다."}</p>}
    {calculation && prediction ? <>
      <div className="evidence-calculations"><div><span>기준 평균기온 · {prediction.observation_date}</span><strong>{number(calculation.current_avg_temperature, 2)}°C</strong><small>어제 확정 일자료 → 내일 예측 (입력일 기준 t+{model?.forecast_offset_days ?? 2})</small></div><div><span>CatBoost 예상 기온</span><strong>{number(calculation.catboost_prediction)}°C</strong><small>{number(calculation.current_avg_temperature)} + ({number(calculation.catboost_residual)}) · 가중치 {number(calculation.catboost_weight * 100, 0)}%</small></div><div><span>LightGBM 예상 기온</span><strong>{number(calculation.lightgbm_prediction)}°C</strong><small>{number(calculation.current_avg_temperature)} + ({number(calculation.lightgbm_residual)}) · 가중치 {number(calculation.lightgbm_weight * 100, 0)}%</small></div></div>
      <div className="evidence-formula"><span>최종 계산식</span><code>{number(calculation.catboost_prediction)} × {number(calculation.catboost_weight, 2)} + {number(calculation.lightgbm_prediction)} × {number(calculation.lightgbm_weight, 2)} = {number(calculation.unrounded_prediction)}°C</code><strong>소수 둘째 자리 반올림 → {number(prediction.predicted_avg_temperature, 2)}°C</strong><small>표시값은 반올림되며, 실제 계산에는 반올림 전 모델 출력값을 사용합니다.</small></div>
      {missing.length ? <p className="evidence-warning">최신 API에 값이 없는 기본 변수 {missing.length}개를 대체 처리했습니다. 아래 표에서 해당 변수와 처리 방법을 확인하세요. API Hub는 기존 44개 변수 전체를 제공하지 않습니다.</p> : null}
      <details className="evidence-details"><summary>실제 기본 입력 {calculation.base_inputs.length}개 · API 원값과 결측 처리 확인</summary><InputTable inputs={calculation.base_inputs} raw /></details>
      <details className="evidence-details"><summary>주요 파생 입력값 확인 · 기온 변화·이동평균·계절성</summary><InputTable inputs={calculation.derived_inputs} /></details>
    </> : <p className="evidence-notice">{error ?? (loading ? "예측 계산을 기다리는 중입니다." : "예측이 생성되면 실제 모델별 출력과 계산식을 표시합니다. 자료가 없으면 계산값을 만들어 표시하지 않습니다.")}</p>}
    {model ? <div className="evidence-training"><h3>학습·검증 근거</h3><p>배포 모델 수집 범위 {date(model.data_start)} ~ {date(model.data_end)} · 학습 입력 종료 {date(model.train_end)} · 검증 입력 종료 {date(model.valid_end)}</p><div className="evidence-table-wrap"><table className="evidence-table"><caption>배포 모델 아티팩트에 기록된 평가 — 아래 재학습 비교와 평가 기간이 다를 수 있습니다.</caption><thead><tr><th scope="col">모델</th><th scope="col">MAE (°C)</th><th scope="col">RMSE (°C)</th><th scope="col">R²</th></tr></thead><tbody>{model.scores.map(score => <tr key={score.model}><th scope="row">{score.model}</th><td>{number(score.mae, 3)}</td><td>{number(score.rmse, 3)}</td><td>{number(score.r2, 4)}</td></tr>)}</tbody></table></div>
      {audit ? <div className="evidence-audit"><h4>최근 로컬 재학습 비교</h4><p>후보: {audit.candidate_version}<br />비교 기존 모델: {audit.compared_model_version}</p><p>학습 {audit.train_rows.toLocaleString()}행 · 검증 {audit.valid_rows.toLocaleString()}행 · 평가 {audit.test_rows.toLocaleString()}행 ({audit.test_start} ~ {audit.test_end}, 입력일 기준)</p><div className="evidence-audit-scores"><span>후보 MAE <b>{number(audit.candidate_mae, 3)}°C</b></span><span>기존 MAE <b>{number(audit.incumbent_mae, 3)}°C</b></span><span>지속성 MAE <b>{number(audit.persistence_mae, 3)}°C</b></span></div><strong>{audit.promotion_approved ? "교체 성능 조건 통과 — 실제 배포 여부는 위 모델 버전으로 확인" : "교체 조건 미충족 · 기존 모델 유지"}</strong><small>시간순 분할·학습 구간 전처리 통계·검증 구간 앙상블 가중치 사용. 재학습은 예측 재시도와 별도입니다. 새 평가 기록은 재학습 후 백엔드 재배포 시 반영됩니다.</small></div> : <p>로컬 재학습 평가 기록이 아직 없습니다.</p>}
    </div> : null}
    <p className="evidence-disclaimer">이 창은 계산 경로와 입력값을 보여줍니다. 변수별 인과관계나 SHAP 기여도 설명은 아닙니다. MAE는 과거 평가 구간의 평균 오차이며 내일 예측의 보장 오차·신뢰구간이 아닙니다. 현재 파이프라인은 별도 통계적 이상치 제거를 수행하지 않습니다. 인증키·인증 URL은 표시하지 않습니다.</p>
  </section>;
}
