import type { InputEvidence, ModelEvidence, Prediction } from "../types";

const number = (value: number | null | undefined, digits = 4) => value == null ? "—" : value.toFixed(digits);
const date = (value: string | null | undefined) => value?.replace(/^(\d{4})(\d{2})(\d{2})$/, "$1-$2-$3") ?? "기록 없음";

function InputTable({ inputs, raw }: { inputs: InputEvidence[]; raw?: boolean }) {
  return <div className="evidence-table-wrap"><table className="evidence-table"><thead><tr><th scope="col">입력 변수</th>{raw ? <th scope="col">최신 API 값</th> : null}<th scope="col">실제 모델 입력값</th><th scope="col">처리 방법</th></tr></thead><tbody>{inputs.map(input => <tr key={input.name}><th scope="row">{input.name}{input.source_key ? <small>{input.source_key}</small> : null}</th>{raw ? <td>{number(input.raw_value)}</td> : null}<td>{number(input.model_value)}</td><td>{input.treatment}</td></tr>)}</tbody></table></div>;
}

export function PredictionEvidence({ prediction, model, error, loading }: { prediction?: Prediction | null; model?: ModelEvidence | null; error?: string; loading: boolean }) {
  const calculation = prediction?.calculation;
  const audit = model?.latest_training;
  const hourly = calculation?.hourly_correction;
  const hourlyAudit = model?.hourly_correction_audit;
  const missing = calculation?.base_inputs.filter(input => input.raw_value == null) ?? [];
  return <section className="evidence-panel panel" aria-labelledby="prediction-evidence-title">
    <div className="evidence-heading"><div><span className="eyebrow">PREDICTION LAB · TRACE</span><h2 id="prediction-evidence-title">예측 온도 계산 근거 및 과정</h2><p>이번 예측의 실제 입력과 계산값을 확인하는 테스트용 분석 창입니다.</p></div><span className="evidence-tag">{calculation ? "실제 추론 기록" : "입력 대기"}</span></div>
    {model ? <>
      <p className="evidence-notice">V2: 동결된 일자료 모델 · V3: V2 + 시간자료 잔차 보정. {model.pipeline_model_version ? `V3 배포 버전: ${model.pipeline_model_version}` : "V3 보정 모델 미준비"}</p>
      <div className="evidence-summary"><div><span>일자료 입력 출처</span><strong>{model.daily_source}</strong><small>기존 44변수 모델 동결 · 시간자료는 별도 보정 모델에만 입력</small></div><div><span>입력 구성 · 일자료 모델 유지</span><strong>기본 {model.base_feature_count} → 파생 포함 {model.engineered_feature_count} → 최종 {model.model_input_count}개</strong><small>{model.hourly_source} · 보정 모델 {model.hourly_correction_ready ? "준비 완료" : "미적용"}</small></div><div><span>동결된 기본 모델</span><strong>{model.model_version}</strong><small>예측 재시도는 재추론만 수행 · 관측 캐시 {model.cache_ttl_seconds / 60}분</small></div></div>
      <div className="evidence-flow" aria-label="예측 처리 과정"><div><b>01</b><h3>관측자료 수집</h3><p>{calculation ? `${calculation.history_start} ~ ${calculation.history_end} · ${calculation.source_row_count}행` : "최근 일자료 조회"}</p><small>서울 ASOS 관측을 날짜순 정렬·중복 제거</small></div><div><b>02</b><h3>전처리·변수 생성</h3><p>44개 변수와 최근 기상 흐름</p><small>강수·적설 등 결측은 0, 나머지는 과거값 ffill → 남은 결측은 학습 중앙값. 1·2·3·7·14일 lag, 3·7·14일 이동통계와 계절 변수를 계산합니다.</small></div><div><b>03</b><h3>기온 변화 예측</h3><p>CatBoost + LightGBM</p><small>관측 평균기온에 각 모델의 예상 변화량을 더합니다.</small></div><div><b>04</b><h3>가중 결합·저장</h3><p>{prediction ? `${prediction.predicted_for_date} 평균기온` : `입력일 기준 t+${model.forecast_offset_days}`}</p><small>검증 구간에서 정한 가중치로 결합. 날짜 확인 후 MySQL 저장.</small></div></div>
    </> : <p className="evidence-notice">{loading ? "모델 근거를 불러오는 중입니다." : "모델 메타데이터를 불러오지 못했습니다."}</p>}
    {calculation && prediction ? <>
      <div className="evidence-calculations"><div><span>기준 평균기온 · {prediction.observation_date}</span><strong>{number(calculation.current_avg_temperature, 2)}°C</strong><small>어제 확정 일자료 → 내일 예측 (입력일 기준 t+{model?.forecast_offset_days ?? 2})</small></div><div><span>CatBoost 예상 기온</span><strong>{number(calculation.catboost_prediction)}°C</strong><small>{number(calculation.current_avg_temperature)} + ({number(calculation.catboost_residual)}) · 가중치 {number(calculation.catboost_weight * 100, 0)}%</small></div><div><span>LightGBM 예상 기온</span><strong>{number(calculation.lightgbm_prediction)}°C</strong><small>{number(calculation.current_avg_temperature)} + ({number(calculation.lightgbm_residual)}) · 가중치 {number(calculation.lightgbm_weight * 100, 0)}%</small></div></div>
      <div className="evidence-formula"><span>동결된 일자료 모델 계산식</span><code>{number(calculation.catboost_prediction)} × {number(calculation.catboost_weight, 2)} + {number(calculation.lightgbm_prediction)} × {number(calculation.lightgbm_weight, 2)} = {number(calculation.unrounded_prediction)}°C</code><strong>기본 예측값 · 기존 모델 가중치와 전처리 변경 없음</strong><small>표시값은 반올림되며, 실제 계산에는 반올림 전 모델 출력값을 사용합니다.</small></div>
      {hourly ? <div className="evidence-audit"><h3>시간자료 오차 보정 · {hourly.status === "applied" ? "적용" : "기본 예측 유지"}</h3><p>{hourly.reason}</p><div className="evidence-audit-scores"><span>기본 예측 <b>{number(hourly.base_prediction, 3)}°C</b></span><span>추정 오차 보정량 <b>{hourly.correction >= 0 ? "+" : ""}{number(hourly.correction, 3)}°C</b></span><span>최종 예측 <b>{number(prediction.predicted_avg_temperature, 2)}°C</b></span></div><code>{number(hourly.base_prediction)} + ({number(hourly.correction)}) = {number(hourly.final_prediction)}°C → {number(prediction.predicted_avg_temperature, 2)}°C</code><p>매일 {hourly.issue_hour}시 기준 · 공개 지연 {hourly.availability_lag_hours}시간 가정 · 최근 72시간 관측 사용</p>{hourly.cutoff_at ? <p>관측 마감: {hourly.cutoff_at} · 기온 관측 {hourly.observed_hours}/72시간 ({number((hourly.coverage ?? 0)*100, 1)}%)<br />보정 모델: {hourly.correction_model_version ?? "미적용"}</p> : null}{hourly.raw_correction != null ? <small>원 보정량 {number(hourly.raw_correction)}°C → ±6°C 제한 → 검증 가중치 {number(hourly.alpha, 2)} 적용</small> : null}{hourly.inputs.length ? <details className="evidence-details"><summary>별도 시간자료 보정 입력 {hourly.feature_count}개 확인 · 일자료 44개와 분리</summary><InputTable inputs={hourly.inputs} /></details> : null}</div> : null}
      {missing.length ? <p className="evidence-warning">최신 API에 값이 없는 기본 변수 {missing.length}개를 대체 처리했습니다. 아래 표에서 해당 변수와 처리 방법을 확인하세요. API Hub는 기존 44개 변수 전체를 제공하지 않습니다.</p> : null}
      <details className="evidence-details"><summary>실제 기본 입력 {calculation.base_inputs.length}개 · API 원값과 결측 처리 확인</summary><InputTable inputs={calculation.base_inputs} raw /></details>
      <details className="evidence-details"><summary>주요 파생 입력값 확인 · 기온 변화·이동평균·계절성</summary><InputTable inputs={calculation.derived_inputs} /></details>
    </> : <p className="evidence-notice">{error ?? (loading ? "예측 계산을 기다리는 중입니다." : "예측이 생성되면 실제 모델별 출력과 계산식을 표시합니다. 자료가 없으면 계산값을 만들어 표시하지 않습니다.")}</p>}
    {model ? <div className="evidence-training"><h3>학습·검증 근거</h3><p>배포 모델 수집 범위 {date(model.data_start)} ~ {date(model.data_end)} · 학습 입력 종료 {date(model.train_end)} · 검증 입력 종료 {date(model.valid_end)}</p><div className="evidence-table-wrap"><table className="evidence-table"><caption>배포 모델 아티팩트에 기록된 평가 — 아래 재학습 비교와 평가 기간이 다를 수 있습니다.</caption><thead><tr><th scope="col">모델</th><th scope="col">MAE (°C)</th><th scope="col">RMSE (°C)</th><th scope="col">R²</th></tr></thead><tbody>{model.scores.map(score => <tr key={score.model}><th scope="row">{score.model}</th><td>{number(score.mae, 3)}</td><td>{number(score.rmse, 3)}</td><td>{number(score.r2, 4)}</td></tr>)}</tbody></table></div>
      {audit ? <div className="evidence-audit"><h4>최근 로컬 재학습 비교</h4><p>후보: {audit.candidate_version}<br />비교 기존 모델: {audit.compared_model_version}</p><p>학습 {audit.train_rows.toLocaleString()}행 · 검증 {audit.valid_rows.toLocaleString()}행 · 평가 {audit.test_rows.toLocaleString()}행 ({audit.test_start} ~ {audit.test_end}, 입력일 기준)</p><div className="evidence-audit-scores"><span>후보 MAE <b>{number(audit.candidate_mae, 3)}°C</b></span><span>기존 MAE <b>{number(audit.incumbent_mae, 3)}°C</b></span><span>지속성 MAE <b>{number(audit.persistence_mae, 3)}°C</b></span></div><strong>{audit.promotion_approved ? "교체 성능 조건 통과 — 실제 배포 여부는 위 모델 버전으로 확인" : "교체 조건 미충족 · 기존 모델 유지"}</strong><small>시간순 분할·학습 구간 전처리 통계·검증 구간 앙상블 가중치 사용. 재학습은 예측 재시도와 별도입니다. 새 평가 기록은 재학습 후 백엔드 재배포 시 반영됩니다.</small></div> : <p>로컬 재학습 평가 기록이 아직 없습니다.</p>}
    </div> : null}
    {hourlyAudit ? <div className="evidence-training"><h3>V2 / V3 검증 비교 · 동일 날짜·시각</h3><p>V3 결합 버전: {hourlyAudit.pipeline_model_version ?? "기록 없음"}<br />시간자료 보정기: {hourlyAudit.model_version} · 기본 V2 SHA-256 {hourlyAudit.base_unchanged ? "무변경 확인" : "불일치"}<br />학습 {hourlyAudit.train_start} ~ {hourlyAudit.train_end} ({hourlyAudit.train_rows}행) · 검증 {hourlyAudit.valid_start} ~ {hourlyAudit.valid_end} ({hourlyAudit.valid_rows}행)<br />평가 {hourlyAudit.test_start} ~ {hourlyAudit.test_end} ({hourlyAudit.test_rows}행, 예측 발행일 기준) · 보정 가능 {hourlyAudit.test_eligible_rows}행, 나머지는 기본값 유지</p><div className="evidence-table-wrap"><table className="evidence-table"><caption>V3의 과거 평가 · 기존 V1/V2 아티팩트 점수와 평가 기간·입력 경로가 다릅니다.</caption><thead><tr><th scope="col">조건</th><th scope="col">검증 MAE</th><th scope="col">평가 MAE</th><th scope="col">평가 RMSE</th></tr></thead><tbody><tr><th scope="row">V2 · 동결 일자료 모델</th><td>{number(hourlyAudit.validation_base_mae, 3)}°C</td><td>{number(hourlyAudit.test_base_mae, 3)}°C</td><td>{number(hourlyAudit.test_base_rmse, 3)}°C</td></tr><tr><th scope="row">V3 · V2 + 시간자료 보정</th><td>{number(hourlyAudit.validation_corrected_mae, 3)}°C</td><td>{number(hourlyAudit.test_corrected_mae, 3)}°C</td><td>{number(hourlyAudit.test_corrected_rmse, 3)}°C</td></tr></tbody></table></div><p>{hourlyAudit.promotion_approved ? "개선 조건 통과" : "개선 조건 미충족 · 보정 미승인"} · 현재 보정 모델 {model?.hourly_correction_ready ? "로드 완료" : "미로드"} · 검증 가중치 {number(hourlyAudit.alpha, 2)}</p><small>과거 공개 시각은 확인되지 않아 1시간 지연을 가정한 실험입니다. 기존 모델 평가에서 이미 열람한 2026년 자료를 포함하므로, 앞으로의 실제 예측에서 추가 검증해야 합니다.</small></div> : null}
    <p className="evidence-disclaimer">이 창은 계산 경로와 입력값을 보여줍니다. 변수별 인과관계나 SHAP 기여도 설명은 아닙니다. MAE는 과거 평가 구간의 평균 오차이며 내일 예측의 보장 오차·신뢰구간이 아닙니다. 일자료 전처리는 그대로이며, 시간자료 보정 단계에서만 물리 범위 밖의 값을 결측으로 처리합니다. 인증키·인증 URL은 표시하지 않습니다.</p>
  </section>;
}
